[package]
name = "wal-telegram-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
xdg = "2.5.2"
regex = "1.9.5"
rand = "0.8.5"
zip = "0.6.6"
